# Generated by Django 5.2.12 on 2026-05-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0030_discount_bookflight_booking_date_bookflight_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookflight',
            name='has_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookflight',
            name='insurance_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookhotel',
            name='has_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookhotel',
            name='insurance_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookpackage',
            name='has_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookpackage',
            name='insurance_cost',
            field=models.IntegerField(default=0),
        ),
    ]
