# Generated by Django 5.2.12 on 2026-05-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0031_bookflight_has_insurance_bookflight_insurance_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookhotel',
            name='breakfast_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookhotel',
            name='checkout_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookhotel',
            name='guest_count',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='bookhotel',
            name='has_breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookhotel',
            name='room_type',
            field=models.CharField(blank=True, choices=[('single', 'Single Room'), ('double', 'Double Room'), ('deluxe', 'Deluxe Room'), ('suite', 'Suite'), ('family', 'Family Room')], default='double', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookhotel',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='hotel_name',
            field=models.CharField(max_length=100),
        ),
    ]
